### ISSUE TITLE
Data/graphics to high solar panels

### ISSUE THREAD

**Issue by Blobke** [SBFspot/SBFspot#392] opened 2020-06-15 17:25 UTC
Hi

I am new to SBFspot and when checking my grapics for my solar panels i see a hugh spike and i have no idea where it comes from.

![image](https://user-images.githubusercontent.com/66966428/84687300-cb7c2c80-af3d-11ea-9d9c-b3be32dff5a5.png)

checking the .CSV file i can't see anything wrong and in the DB in vwdaydata everything looks fine at first sight.

Anyone an idea where this is coming from?

**Comment by Blobke** [comment] 2020-06-15 17:37
Hi

Here is a more detail screenshot

![image](https://user-images.githubusercontent.com/66966428/84688473-b0aab780-af3f-11ea-8cbf-163fae69f9f1.png)

**Comment by sbf-** [comment] 2020-06-15 22:10
From where do you take the data for the graphs? CSV or SQL DB?
If you see it in the graph, you should see it in the datasource too.

**Comment by Blobke** [comment] 2020-06-16 10:18
Hi

I have checked the .CSV files and the DB but i can't explain the spike

[SBFspot.zip](https://github.com/SBFspot/SBFspot/files/4785974/SBFspot.zip)

I have added the CSV & the DB? Maybe someone can see what is wrong?

**Comment by sbf-** [comment] 2020-06-17 12:56
There is nothing wrong in the db/csv so the problem is in your graphical tool.
What is the data source of your graph?

**Comment by Blobke** [comment] 2020-06-17 16:50
Hi

where can i see what data source the graph is taking?

**Comment by sbf-** [comment] 2020-06-17 17:57
You don't know and we don't know ;-)
We don't even know what visualization software you're using.
This is not SBFspot related, so I'll close this issue

**Closed by sbf-** 2020-06-17 17:57 UTC

**Comment by Blobke** [comment] 2020-06-19 14:36
Hi

Yes i have found where the issue is and it is in the domoticz.db, the meter table.
It is recording there with 2 digits to much.

I have posted this in the domoticz forum.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=33107

thx anyway for the help.
