### ISSUE TITLE
Unknown inverter Type

### ISSUE THREAD

**Issue by DerKammi** [SBFspot/SBFspot#291] opened 2019-04-21 12:00 UTC
0x00002481 and Inverter Type=<Fill in the exact type> (e.g. SB1300TL-10)
SUSyID: 378 - SN: xxxxxxxxx
Device Name:      STP5.0-3AV-40 099

SBFspot V3.5.1

**Comment by sbf-** [comment] 2019-04-22 07:13
Duplicate of #287 
Replace taglist.txt files

**Closed by sbf-** 2019-04-22 07:13 UTC
